export const FORM_BUILDER = {
    TOOLS: {
        FIELDS: [
            { label: 'Text input', description: 'Single line text input', icon: 'ri-text' },
            { label: 'Number input', description: 'Input field that only allows numbers', icon: 'ri-numbers-fill' },
            { label: 'Email address', description: 'Text field that expects an email', icon: 'ri-mail-add-fill' },
            { label: 'Phone number', description: 'Phone number with country selector', icon: 'ri-phone-fill' },
            { label: 'Password', description: 'Text field that expects a password', icon: 'ri-key-2-fill' },
            { label: 'URL', description: 'Text field that expects an URL', icon: 'ri-links-fill' },
            { label: 'Location', description: 'Google places location input', icon: 'ri-map-pin-fill' },
            { label: 'Textarea', description: 'Single line or multiline text area', icon: 'ri-text-block' },
            { label: 'WYSIWYG editor', description: 'Rich text editor', icon: 'ri-italic' },
            { label: 'Signature', description: 'Draw, type or upload signature', icon: 'ri-sketching' },
            { label: 'Checkbox', description: 'Plain checkbox input', icon: 'ri-checkbox-fill' },
            { label: 'Checkbox group', description: 'Plain checkbox options', icon: 'ri-list-check-3' },
            { label: 'Checkbox blocks', description: 'Checkbox options as blocks', icon: 'ri-news-fill' },
            { label: 'Checkbox tabs', description: 'Checkbox options masked as tabs', icon: 'ri-archive-drawer-fill' },
            { label: 'Radio', description: 'Plain radio input', icon: 'ri-radio-button-fill' },
            { label: 'Radio group', description: 'Plain Radio options', icon: 'ri-list-radio' },
            { label: 'Radio blocks', description: 'Radio options as blocks', icon: 'ri-pages-fill' },
            { label: 'Radio tabs', description: 'Radio options masked as tabs', icon: 'ri-archive-drawer-line' },
            { label: 'Matrix', description: 'A matrix of input fields', icon: 'ri-layout-grid-2-fill' },
            { label: 'Toggle', description: 'Toggle / switch button', icon: 'ri-toggle-fill' },
            { label: 'Select', description: 'Select input', icon: 'ri-expand-up-down-fill' },
            { label: 'Multiselect', description: 'Multiselect input', icon: 'ri-group-2-fill' },
            { label: 'Tags', description: 'Tags input', icon: 'ri-bookmark-fill' },
            { label: 'Date', description: 'Datepicker input', icon: 'ri-calendar-fill' },
            { label: 'Datetime', description: 'Date & time picker input', icon: 'ri-calendar-schedule-fill' },
            { label: 'Time', description: 'Time picker input', icon: 'ri-time-fill' },
            { label: 'Multiple dates', description: 'Date picker that allows multiple dates', icon: 'ri-calendar-2-fill' },
            { label: 'Date range', description: 'Date picker that allows date range', icon: 'ri-calendar-event-fill' },
            { label: 'Slider', description: 'Horizontal slider', icon: 'ri-equalizer-2-fill' },
            { label: 'Range slider', description: 'Horizontal slider with range', icon: 'ri-equalizer-fill' },
            { label: 'Vertical slider', description: 'Vertical slider', icon: 'ri-sound-module-fill' },
            { label: 'File upload', description: 'File upload input', icon: 'ri-file-3-fill' },
            { label: 'Multi-file upload', description: 'Multi-file upload input', icon: 'ri-file-list-3-fill' },
            { label: 'Image upload', description: 'File upload with image only', icon: 'ri-image-fill' },
            { label: 'Multi-image upload', description: 'Multi-file upload with images only', icon: 'ri-multi-image-fill' },
            { label: 'Gallery', description: 'Multi-image upload with gallery view', icon: 'ri-gallery-fill' },
            { label: 'Captcha', description: 'Prevents submission by robots', icon: 'ri-robot-2-fill' },
            { label: 'Hidden input', description: 'Single line or multiline text area', icon: 'ri-eye-off-fill' },
        ],
        STATIC: [
            { label: 'Submit button', description: 'Button that triggers submit', icon: 'ri-check-fill' },
            { label: 'Reset button', description: 'Button that triggers reset', icon: 'ri-refresh-fill' },
            { label: 'Primary button', description: 'Button with primary color', icon: 'ri-star-s-fill' },
            { label: 'Secondary button', description: 'Button with gray color', icon: 'ri-star-half-fill' },
            { label: 'Danger button', description: 'Button with danger color', icon: 'ri-alarm-warning-fill' },
            { label: 'H1 header', description: 'HTML <h1> tag', icon: 'ri-h-1' },
            { label: 'H2 header', description: 'HTML <h2> tag', icon: 'ri-h-2' },
            { label: 'H3 header', description: 'HTML <h3> tag', icon: 'ri-h-3' },
            { label: 'H4 header', description: 'HTML <h4> tag', icon: 'ri-h-4' },
            { label: 'H5 header', description: 'HTML <h5> tag', icon: 'ri-h-5' },
            { label: 'H6 header', description: 'HTML <h6> tag', icon: 'ri-h-6' },
            { label: 'Paragraph', description: 'HTML <p> tag', icon: 'ri-paragraph' },
            { label: 'Quote', description: 'HTML <quote> tag', icon: 'ri-double-quotes-l' },
            { label: 'Image', description: 'HTML <img> tag', icon: 'ri-image-2-line' },
            { label: 'Link', description: 'HTML <a> tag', icon: 'ri-link' },
        ],
        STRUCTURES: [
            { label: '2 columns', description: 'Two columns next to each other', icon: 'ri-text' },
            { label: 'One Column', description: 'Single line text input', icon: 'ri-text' },
            { label: 'One Column', description: 'Single line text input', icon: 'ri-text' },
            { label: 'One Column', description: 'Single line text input', icon: 'ri-text' },
            { label: 'One Column', description: 'Single line text input', icon: 'ri-text' },
            { label: 'One Column', description: 'Single line text input', icon: 'ri-text' },
            { label: 'One Column', description: 'Single line text input', icon: 'ri-text' },
            { label: 'One Column', description: 'Single line text input', icon: 'ri-text' },
            { label: 'One Column', description: 'Single line text input', icon: 'ri-text' },
        ]
    }
}